---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: jupyterhub-backup-launcher
  labels:
    app.kubernetes.io/name: {{ include "jupyterhub-kubernetes-backup.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  schedule: {{ .Values.cronJob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronJob.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ .Release.Name }}
          labels:
            app.kubernetes.io/name: {{ include "jupyterhub-kubernetes-backup.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        spec:
          restartPolicy: Never
          {{- if .Values.serviceAccount.create }}
          serviceAccountName: {{ template "jupyterhub-kubernetes-backup.serviceAccountName" . }}
          {{- end }}
          containers:
          - name: jupyterhub-backup-launcher
            image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["/usr/local/bin/k8s-job-backup-launcher"]
            env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BACKUP_IMAGE_NAME
              value: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
            - name: BACKEND
              value: "{{ .Values.backend.type }}"
            - name: LOG_LEVEL
              value: "{{ .Values.log.level }}"
            - name: LOG_FORMAT
              value: "{{ .Values.log.format }}"
            - name: BACKUP_POD_NODE_AFFINITY
              value: "{{ .Values.backup.podNodeAffinity }}"
            {{- if .Values.backend.s3 }}
            {{- if .Values.backend.s3.bucket }}
            - name: BACKEND_S3_BUCKET
              value: "{{ .Values.backend.s3.bucket }}"
            {{- end }}
            {{- if .Values.backend.s3.prefix }}
            - name: BACKEND_S3_PREFIX
              value: "{{ .Values.backend.s3.prefix }}"
            {{- end }}
            {{- if .Values.backend.s3.existingSecret }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.s3.existingSecret }}
                  key: aws-access-key-id
            {{- else if .Values.backend.s3.accessKey }}
            - name: AWS_ACCESS_KEY_ID
              value: "{{ .Values.backend.s3.accessKey }}"
            {{- end }}
            {{- if .Values.backend.s3.existingSecret }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.s3.existingSecret }}
                  key: aws-secret-access-key
            {{- else if .Values.backend.s3.secretKey }}
            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ .Values.backend.s3.secretKey }}"
            {{- end }}
            {{- if .Values.backend.s3.region }}
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.backend.s3.region }}"
            {{- end }}
            {{- end }}
            resources:
              {{ toYaml .Values.resources | nindent 14 }}
