{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jupyterhub-kubernetes-backup.serviceAccountName" . }}
  labels:
    {{- include "jupyterhub-kubernetes-backup.labels" . | trim | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "jupyterhub-kubernetes-backup.fullname" . }}
  labels:
    {{- include "jupyterhub-kubernetes-backup.labels" . | trim | nindent 4 }}
rules:
- apiGroups: ["batch", "extensions"]
  resources:
  - jobs
  verbs: ["create", "get", "list", "watch"]
- apiGroups: [""]
  resources:
  - persistentvolumeclaims
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "jupyterhub-kubernetes-backup.fullname" . }}
  labels:
    {{- include "jupyterhub-kubernetes-backup.labels" . | trim | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "jupyterhub-kubernetes-backup.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "jupyterhub-kubernetes-backup.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
