name: CI
on: [push, pull_request]
jobs:
  test:
    name: go-${{ matrix.go }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        go: ['1.19', '1.20', '1.21']
      fail-fast: false
    env:
      GO_VERSION: ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - run: make test
    - uses: codecov/codecov-action@v1
      with:
        env_vars: GO_VERSION

  helm:
    name: Helm
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: helm lint .
      working-directory: chart/jupyterhub-kubernetes-backup
    - name: Template
      run: helm template .
      working-directory: chart/jupyterhub-kubernetes-backup
