name: CI
on: [push, pull_request]
jobs:
  test:
    name: go-${{ matrix.go }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        go: ['1.13', '1.14', '1.15']
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: make test